url: 'http://localhost:8000'
host: '0.0.0.0'
port: 8000

timeout: 30
timeout-message: 'Code execution timed out after 30 seconds'

black-list:
- 'input()'
- 'open('
black-list-message: 'input() and open() is unavailable!'

short-link: false
short-link-service: "my" # "goo.su" or "my"
goo.su:
  environ: false
  goo.su-apikey: 'None'
my:
  environ: false
  url: ''
  headers: "{'Content-Type': 'application/json','x-api-token': ''}"
  data-url: "url"
  response: 'short_url'